# Generated by Django 4.2.11 on 2024-05-03 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_menu_options_remove_menu_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Меню", "verbose_name_plural": "Меню"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="description",
        ),
    ]
