# Generated by Django 4.2.11 on 2024-05-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0007_alter_menuitem_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.menu",
                verbose_name="Родитель",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
