version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/menu
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  media:
  static:
  postgres_data:
